name: Build Desktop App

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      # Risolve il problema del "Permission Denied" su macOS e Linux
      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle
        shell: bash # Forza l'uso di Bash anche su Windows per far funzionare l'if/else
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew packageReleaseMsi
          elif [ "$RUNNER_OS" == "Linux" ]; then
            ./gradlew packageReleaseDeb
          elif [ "$RUNNER_OS" == "macOS" ]; then
            ./gradlew packageReleaseDmg
          fi

      - name: Print jpackage error log
        if: failure()
        run: cat desktopApp/build/compose/logs/createReleaseDistributable/jpackage-*-err.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: musikl-build-${{ matrix.os }}
          path: |
            desktopApp/build/compose/binaries/main-release/msi/*
            desktopApp/build/compose/binaries/main-release/deb/*
            desktopApp/build/compose/binaries/main-release/dmg/*